container:
  image: ubuntu:latest

env:
  ## Need To Fill
  # Sync - Requierd
  ROM_NAME: ""
  ANDROID_VERSION: ""
  REPO_URL: ""
  REPO_BRANCH: ""
  MANIFEST_URL: ""
  MANIFEST_BRANCH: ""

  # Build - Requierd 
  DEVICE_CODENAME: ""
  AUTO_BRINGUP: ""
  LUNCH_NAME: ""
  BACON_NAME: ""

  # Upload stuff - Optional
  UPLOAD_TYPE: ""
  UPLOAD_RECOVERY: ""
  TG_USER: ""

  # Google Drive - Optional
  GD_PATH: ""

  # Github Releases - Optional
  GH_USERNAME: ""
  GH_REPO: ""

  # SourceForge - Optional
  SF_USER: ""
  SF_PASS: ""
  SF_PROJECT: ""
  SF_PATH: ""

  # Telegram - Optional
  TG_TOKEN: ""
  TG_CHAT: ""

check_task:
  compile_script: sh -c 'printf "build-bot cirrusci\n" && apt-get update -y && apt-get install sudo -y && sh first_time.sh && source build.sh'
